version: '3.8'
services:
  db:
    container_name: musky-huskle-db
    image: mysql:latest
    restart: always
    volumes:
      - ./packages/backend/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  backend:
    container_name: musky-huskle-server
    build:
      dockerfile: ./DockerFile.backend
    depends_on:
      - db
  proxy:
    container_name: musky-huskle-proxy
    image: envoyproxy/envoy:v1.30-latest
    ports:
      - 8080:8080 #since our frontend is still mocked, we expose the proxy port to make gRPC requests to the server
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    environment:
      - loglevel=debug
  frontend: #still mocked, backend is not accessible by it
    container_name: musky-huskle-interface
    build:
      dockerfile: ./DockerFile.frontend
    ports:
      - 5173:5173