FROM node:18-alpine AS development

WORKDIR /front/src/muskyhuskle

ADD ./packages/frontend/package.json /front/src/muskyhuskle/

RUN yarn install

ADD ./packages/frontend/. /front/src/muskyhuskle/

CMD [ "yarn", "dev" ]