apiVersion: apps/v1
kind: Deployment
metadata:
  name: musky-huskle-db
  namespace: default
  labels:
    app: musky-huskle-db
spec:
    replicas: 1
    selector:
      matchLabels:
        app: musky-huskle-db
    template:
      metadata:
          labels:
            app: musky-huskle-db
      spec:
        containers:
          - name: musky-huskle-db
            image: mysql:latest
            imagePullPolicy: IfNotPresent
            ports:
              - containerPort: 3306
            env:
              - name: MYSQL_DATABASE
                valueFrom:
                  configMapKeyRef:
                    name: musky-huskle-db
                    key: database
              - name: MYSQL_USER
                valueFrom:
                  secretKeyRef:
                    name: musky-huskle-db
                    key: username
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: musky-huskle-db
                    key: password
              - name: MYSQL_ROOT_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: musky-huskle-db
                    key: password
            resources:
              requests:
                memory: "1Gi"
                cpu: "500m"
              limits:
                memory: "2Gi"
                cpu: "4"
            volumeMounts:
              - name: musky-huskle-storage
                mountPath: /var/lib/mysql
        volumes:
        - name: musky-huskle-storage
          persistentVolumeClaim:
            claimName: musky-huskle-pv-claim