apiVersion: v1
kind: PersistentVolume
metadata:
  name: musky-huskle-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/muskyhuskle"
    type: DirectoryOrCreate
