apiVersion: v1
kind: Service
metadata:
  name: musky-huskle-db
  labels:
    run: musky-huskle-db
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: musky-huskle-db
