apiVersion: v1
kind: Service
metadata:
  name: musky-huskle-server
  labels:
    run: musky-huskle-server
spec:
  ports:
    - port: 9621
      targetPort: 9621
      protocol: TCP
  selector:
    app: musky-huskle-server
