apiVersion: v1
kind: Service
metadata:
  name: musky-huskle-server
  labels:
    run: musky-huskle-server
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: musky-huskle-server
