apiVersion: v1
kind: Service
metadata:
  name: musky-huskle-frontend
  labels:
    run: musky-huskle-frontend
spec:
  ports:
    - port: 80
      targetPort: 5173
      protocol: TCP
  selector:
    app: musky-huskle-frontend
